#alias
    alias l='ll'
    alias ll='ls -l'
    alias la='ls -a'
    alias lA='ls -A'
    alias ls='ls --color=auto'
alias du='du -h'
alias df='df -h'
alias ps='ps -A'
alias vi='vim'
#alias make='make -j5'
alias mk='make'
alias grep='grep --exclude-dir=.git --exclude-dir=.svn'
alias cls='clear'
alias hist='history|tail'
alias h10='history|tail -n10'
alias explorer='xdg-open'
#php unit
alias phpunit='phpunit --stderr'
alias mc='mc --nocolor'
alias caja='caja --no-desktop'
alias rsync='rsync --progress'
alias ssh='ssh -X'