#apt related
#alias ainstall='sudo apt-get install -y'
#alias ai='sudo apt-get install -y'
#alias ainst='sudo apt-get install -y'
#alias areinstall='sudo apt-get install --reinstall -y'
#alias aremove='sudo apt-get remove'
#alias apurge='sudo apt-get purge'
#alias asearch='apt-cache search'
#alias aupdate='sudo apt-get update'
#alias apdate='sudo apt-get update'
#alias asource='apt-get source'
#alias asrc='apt-get source'
#alias afile='dpkg -L'
#alias dfile='dpkg -L'
#alias alist='dpkg -l |grep '
#alias dlist='dpkg -l'
#alias aowner='dpkg -S'
#alias downer='dpkg -S'
#alias ainfo='dpkg -s'
#alias dinfo='dpkg -s'
#alias atry='dpkg --dry-run'
#alias dinst='sudo dpkg -i'
#alias di='sudo dpkg -i'
#alias abuild='sudo apt-get build-dep -y'

